[package]
name = "pluginci"
version = "0.1.0"
authors = ["doomy <alexanderpaullozada@gmail.com>"]
# edition = "2018"
crate-type = ["cdylib"]

[dependencies]
vst = { git = "https://github.com/rust-dsp/rust-vst" }